### PR TITLE
Add .fstat singleton method

### PR DESCRIPTION
**Pull request by hirura**
This PR adds `.fstat` singleton method to the `Sys::Filesystem` class.

On Unix systems, this is a wrapper around the fstatvfs() or fstatvfs64() system calls. The method takes an instance of `File` or `Dir`, and calls fstatvfs() system call with its file descriptor value (`File#fileno` or `Dir#fileno`). When a file is created with `File::Constants::TMPFILE` flag, `Sys::Filesystem::Stat#path` returns `nil` because it does not have pathname.

On Windows system, just pass the pathname of the file to the .stat method.

```ruby
# normal file
file = File.open("pathname", "r")
Sys::Filesystem.fstat(file)

# directory
file = Dir.open("/")
Sys::Filesystem.fstat(file)

# tmpfile
file = File.open("/tmp", File::RDWR | File::TMPFILE)
Sys::Filesystem.fstat(file).path # => nil
```

### CODE REVIEW

**Comment by djberg96** [comment]
@hirura Thanks! I like the idea in principle, but I think rather than create a separate singleton method, it would be better to overload the existing method like so:

`path = path.path if path.respond_to?(:path)`

This is basically what you did for the Windows implementation anyway.

**Comment by hirura** [comment]
@djberg96 Thanks for the comment.

One of the reason I added the new .fstat method is for users who are familiar with UNIX system calls not to be confused what kind of argument to be passed to the method.
And in my opinion, the reason to use fstatvfs(), or fstat(), is that we can believe the file is still on the filesystem, even its pathname is not available (it may be moved, unlinked or removed). In case .fstat method calls .stat method internally, we would need to check if the pathname is still available or receive some errors, which would be, personally, making confusion.
This is why I added fstatvfs() system call.

If you prefer .fstat to use .stat internally, I will update the PR with the way.

**Comment by djberg96** [comment]
@hirura Well, the idea is to abstract away the unix-isms into a single unified interface since this is a cross-platform library. You could argue that it's already too late since there's `stat` method, but I'd rather not compound it. :)

I'm not going to worry about temp files that don't have a `path` attribute, since you're not supposed to be caring about them anyway.

**Comment by hirura** [comment]
@djberg96 Okay, then my understanding is that:

- Remove `attach_function(:fstatvfs, ...` from unix's functions.rb
- Call `.stat` in `.fstat` method with the pathname by `File#path` (use same way on both unix and windows)

Is the above update what you commented ?

**Comment by hirura** [comment]
Sorry, you are saying that `.stat` method to take `File` or `Dir` instance as an argument ?

**Comment by djberg96** [comment]
@hirura Yep, let the .stat method take anything that responds to a `.path` method.

**Comment by hirura** [comment]
@djberg96 Thanks, I will update and push that.

**Comment by hirura** [comment]
@djberg96 I have fixed the code. Could you take a look? Thanks.

**Comment by djberg96** [comment]
@hirura Looks good, thanks!

**Pull request merged**
